### ISSUE TITLE
ImportError: cannot import name 'slice_X' 

### ISSUE THREAD

**Issue by alphaaurigae** [btc-room101/bitcoin-rnn#4]
Ubuntu 18.04 | keras 2.2.4
```

~/bitcoin-rnn [master|✚ 1] 
03:32 $ python3 gru-addr2priv.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "gru-addr2priv.py", line 23, in <module>
    from keras.engine.training import slice_X
ImportError: cannot import name 'slice_X'
```

when i change the source of according to this [https://stackoverflow.com/questions/42852495/where-did-keras-function-slice-x-go](https://stackoverflow.com/questions/42852495/where-did-keras-function-slice-x-go)

https://pastebin.com/cLA5PAev

i end up with 
```
~/bitcoin-rnn [master|✔] 
03:39 $ python3 gru-addr2priv.py 
Using TensorFlow backend.
Reading privaddr-pair.txt Lines 71

Generating data...
Traceback (most recent call last):
  File "gru-addr2priv.py", line 126, in <module>
    q = contents[i] # remove char > MAXLEN
IndexError: list index out of range
```
any suggestion how to fix this?

**Comment by aiyulu1** [comment]
you need python2.7 and keras==1.2.2 and tensorflow / tensorflow-gpu 1.x version
you can here find https://github.com/fo40225/tensorflow-windows-wheel
